### ISSUE TITLE
Copy Lang Dir from Source to Build Dir when running ./build.sh

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#10]
<img width="429" alt="Bildschirmfoto 2020-06-25 um 09 39 48" src="https://user-images.githubusercontent.com/4953/85678021-5f7d8f00-b6c8-11ea-81c6-2198054e0e5b.png">

**Comment by zdavatz** [comment]
this does not work: `cd /Users/zdavatz/software/amiko_linux`  and `cp -r lang/ build/`

**Comment by zdavatz** [comment]
this also does not work `cp -r lang build/AmiKo-wx/AmiKo-wx-mk/`

**Comment by zdavatz** [comment]
this works: `cp -r lang /Users/zdavatz/software/amiko_linux/build/AmiKo-wx/AmiKo-wx-xc/Debug`

**Comment by bettar** [comment]
The destination location depends on the particular generator used. Not easy to predict what generator the developer selects in configuration file seed.conf. This action more appropriately belongs to the installer.

**Comment by zdavatz** [comment]
put `STEP_COPY_LANG_FILES=y` into `steps.conf`, see https://github.com/zdavatz/amiko_linux#amiko_linux
