### ISSUE TITLE
We should use `PRIMARY KEY` for KEY_ROWID

### ISSUE THREAD

**Issue by b123400** [zdavatz/amiko_linux#103]
The current implementation of KEY_ROWID is only `INTEGER`, which means it is possible to have multiple rows with the same id, it is not safe:

https://github.com/zdavatz/amiko_linux/blob/10b4deee33a0ae5f290412a5d3677892cbbd3a11/PatientDBAdapter.cpp#L70

The id increment is also done manually, which means we may see inconsistency when multiple threads are interacting with the database, e.g. Syncing with Google drive in background.
https://github.com/zdavatz/amiko_linux/blob/10b4deee33a0ae5f290412a5d3677892cbbd3a11/gui/PatientSheet.cpp#L206

The correct way would be setting it to `INTEGER PRIMARY KEY` like what we have on Android:

https://github.com/zdavatz/AmiKo-Android/blob/336d258acdfcbe07e62f2ad12617df19ee106a06/src/main/java/com/ywesee/amiko/PatientDBAdapter.java#L61

Or even better with `INTEGER PRIMARY KEY AUTOINCREMENT`.

https://github.com/zdavatz/amiko_csharp/blob/1af6f4f39aca937589c8a39490fd959a1691e30b/AmiKoWindows/Source/PatientDb.cs#L77

This way we don't have to specify the id ourselves, Sqlite will automatically do that for us.

**Comment by zdavatz** [comment]
I agree.

**Comment by bettar** [comment]
It sounds like a good idea. That implementation has been ported from the amiko-osx project, I don't know if it would be an issue for amiko-osx too. Actually, I am not sure if that column in the patient database is currently used for anything at all.

**Comment by zdavatz** [comment]
In macOS and iOS we use CoreData.

**Comment by b123400** [comment]
In CoreData, uniqueness is managed via NSManagedObjectID https://developer.apple.com/documentation/coredata/nsmanagedobjectid 
I am not sure if we are using that though. I think the most important thing is to have `uniqueId` being really unique.

**Comment by bettar** [comment]
`uniqueId` is already unique, it's a different column in the database.
`rowId` should be improved like you suggested, but I think it was not used in the old amiko-osx, it's not used  in the latest amiko-osx, it's not used in amiko-linux.
