### ISSUE TITLE
Installation to CONFIG_BIN_DIR is not longer working.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#116]
![Bildschirmfoto 2020-12-29 um 21 10 59](https://user-images.githubusercontent.com/4953/103311382-853e7480-4a1a-11eb-9c9e-58e6ae5c1df9.png)
![Bildschirmfoto 2020-12-29 um 21 08 50](https://user-images.githubusercontent.com/4953/103311388-88396500-4a1a-11eb-881d-d5f99d1074f8.png)
![Bildschirmfoto 2020-12-29 um 16 28 25](https://user-images.githubusercontent.com/4953/103311393-8bccec00-4a1a-11eb-945c-e5d2e9e3c1c6.png)

Installation should go into `CONFIG_BIN_DIR`

**Comment by zdavatz** [comment]
Now we have two routes: install with deb or install from sources

**Comment by bettar** [comment]
What do you mean by "no longer working" ?

**Comment by zdavatz** [comment]
the `AmiKo` Binary is not up-to-date after running `build.sh`.
