### ISSUE TITLE
Add Desitin splash screen for AmiKo and Desitin

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#120]
1. Add Desitin splash screen for AmiKo and CoMed. 
2. See macOS App Store or Windows App Store versions as example. Use the same image for the Splash Screen.
2. The Splash screen for CoMed has a blue background.
3. AmiKo and CoMed have different splash screen.

**Comment by b123400** [comment]
I took a look at Amiko-osx, both AmiKo and CoMed has white background:
https://github.com/zdavatz/amiko-osx/blob/master/AmiKoOSX/amikoosx_splash_1000x670.png
https://github.com/zdavatz/amiko-osx/blob/master/AmiKoOSX/comedosx_splash_1000x670.png

**Comment by zdavatz** [comment]
Ah, ok, then I confused it with the pill Logo in the App. Lets take the above then.
