### ISSUE TITLE
Error running Javascript in Interactions.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#123]
1. Click on Interactions Icon results in 
2. Adding something to the interactions basket results in 

![Bildschirmfoto 2021-01-01 um 16 35 54](https://user-images.githubusercontent.com/4953/103441624-8b696680-4c4f-11eb-92a6-f4dc4babd4e5.png)

**Comment by bettar** [comment]
Cannot reproduce on the macOS build

**Comment by zdavatz** [comment]
This error happens on Mandravia Linux as well.
