### ISSUE TITLE
In-Text-Search is not working on macOS Version

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#132]
1. Start macOS App.
2. Search for "Ponstan".
3. Select "Ponstan".
4. Search for any word in the Fachinfo of "Ponstan".
5. Highlighting and Search for the word is not working.
Note: Works well on the Linux version.

**Comment by b123400** [comment]
https://github.com/zdavatz/amiko_wx/blob/a6d079f00de33fdf66ee276ace624a9cc5b0307c/gui/MainWindow.cpp#L2725
As Alex wrote here, it is not supported on Mac yet.

The official documentation says:
> This always returns wxNOT_FOUND on the macOS WebKit backend. 
https://docs.wxwidgets.org/trunk/classwx_web_view.html#a75b8b033d2a1a45f8c491c3da2c96312

So this is not a bug, and if it has to be implemented, we probably need to use Javascript and inject into the webview, similar to Amiko-Android's way.

**Comment by zdavatz** [comment]
ok, good to know. Lets implement it.
