### ISSUE TITLE
Fachinfo In-Text-Search

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#14]
This seems to work on Lubuntu:
![20200703_fi_search](https://user-images.githubusercontent.com/4953/86448788-8f0b4780-bd17-11ea-9983-04ebb7adf11e.png)
@bettar please state your Webkit version, Kernel version and Ubuntu version.

**Comment by bettar** [comment]
Ubuntu 18.04.4 LTS
kernel 5.3.0-62-generic
webkit2gtk-4.0, version 2.28.2

**Comment by zdavatz** [comment]
What does this show: `apt-cache rdepends webkit2gtk-4.0`

**Comment by bettar** [comment]
[rdepends.txt](https://github.com/zdavatz/amiko_linux/files/4868678/rdepends.txt)

**Comment by zdavatz** [comment]
Must be related to the GTK-Version.

**Comment by zdavatz** [comment]
works fine on Gentoo as well:

![latest-screenshot](https://user-images.githubusercontent.com/4953/86453163-a1887f80-bd1d-11ea-8a89-3462b706e240.png)

**Comment by zdavatz** [comment]
4e0c301de19194971e93ff90deee7339cd5a304b
