### ISSUE TITLE
Open PDF on macOS and Linux in Default browser.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#157]
1. Start App.
2. Select FTS search.
3. Search for `dhpc`
4. Select a product.
5. Click on PDF link at the bottom.
6. Open PDF on macOS and Linux in Default browser.

**Comment by b123400** [comment]
On my mac it opens like this:

![AmiKo Desitin 2021-03-13 13-29-19](https://user-images.githubusercontent.com/127193/111019056-21fc9580-8400-11eb-87b4-378969c37e3b.png)

Or should it be opened in a browser?

**Comment by zdavatz** [comment]
Does it open on Linux to?

**Comment by zdavatz** [comment]
Ok, lets always open the PDF links in the default Browser on all OS.
