### ISSUE TITLE
Skipping a deployment with the releases provider because this branch is not permitted: master

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#192]
1. See: https://travis-ci.com/github/zdavatz/amiko_wx/builds/224692404#L4134
2. ARM build is missing here: https://github.com/zdavatz/amiko_wx/releases/tag/0.1.289

**Comment by b123400** [comment]
Das Problem ist hier https://travis-ci.com/github/zdavatz/amiko_wx/builds/224693796

**Comment by b123400** [comment]
Ich denke dass, die API Key ist falsch

```
/home/travis/.rvm/gems/ruby-2.7.0/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://docs.github.com/rest (Octokit::Unauthorized)
```

**Comment by zdavatz** [comment]
Du meinst den Key auf Zeile 63 im `.travis.yml`?

**Comment by zdavatz** [comment]
Ich brauche nur diese Credentials?

![Bildschirmfoto 2021-05-02 um 15 32 57](https://user-images.githubusercontent.com/4953/116814991-c1661b00-ab5b-11eb-8925-22d8e8dbcf6d.png)

**Comment by zdavatz** [comment]
![Bildschirmfoto 2021-05-02 um 16 06 21](https://user-images.githubusercontent.com/4953/116816061-b06bd880-ab60-11eb-9757-2b2ffca2dc1d.png)

**Comment by zdavatz** [comment]
https://docs.travis-ci.com/user/github-oauth-scopes/#repositories-on-httpstravis-ciorg

**Comment by zdavatz** [comment]
https://travis-ci.com/github/zdavatz/amiko_wx/builds/

**Comment by zdavatz** [comment]
~/.software/amiko_linux> `travis enable`
zdavatz/amiko_wx: enabled :)

**Comment by zdavatz** [comment]
1. `travis login --pro --github-token ghp_***`
2. `travis encrypt --com -r zdavatz/amiko_wx ghp_*** --add deploy.api_key`
