### ISSUE TITLE
Compare Favorites file format with Windows version

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#20]
see: https://github.com/zdavatz/amiko_csharp/issues/234

**Comment by zdavatz** [comment]
[AmiKo Desitin_zip.zip](https://github.com/zdavatz/amiko_linux/files/4913321/AmiKo.Desitin_zip.zip)

**Comment by bettar** [comment]
What is the above zip file "AmiKo Desitin_zip.zip" ?

**Comment by zdavatz** [comment]
> What is the above zip file "AmiKo Desitin_zip.zip" ?

It is the Windows-AmiKo-Home-Dir with all the data.
