### ISSUE TITLE
AmiKo Icon does not show in sidebar on Ubuntu

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#21]
<img width="489" alt="Bildschirmfoto 2020-07-15 um 18 54 31" src="https://user-images.githubusercontent.com/4953/87567318-d35df680-c6cc-11ea-8cb8-28aaaa9b1910.png">

**Comment by bettar** [comment]
There is no installer yet, so it's to be expected that the sidebar icon is missing. Simple running `make install` is not an installer.
