### ISSUE TITLE
Interaction Favorites are not properly filtered

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#22]
Unstarred items should not be shown when selecting the FTS favorites.

<img width="559" alt="Bildschirmfoto 2020-07-15 um 18 58 57" src="https://user-images.githubusercontent.com/4953/87568128-d3122b00-c6cd-11ea-8969-f211bacc351e.png">

Also: selecting more then one Favorite after each other can result in one Favorites being deselected again.

**Comment by bettar** [comment]
This seems to happen in amino-osx as well, which is used as reference for the implementation

**Comment by zdavatz** [comment]
Store Version of AmiKo Desitin macOS works well.

**Comment by zdavatz** [comment]
<img width="564" alt="Bildschirmfoto 2020-07-16 um 11 43 49" src="https://user-images.githubusercontent.com/4953/87649952-a0157900-c759-11ea-957c-d5d100b3fd74.png">
