### ISSUE TITLE
Timestamp at the Bottom of the FI does not correspond to the files in the Home Dir.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#23]
<img width="466" alt="Bildschirmfoto 2020-07-15 um 19 30 31" src="https://user-images.githubusercontent.com/4953/87570670-a829d600-c6d1-11ea-96ff-e5a8a64b7325.png">

<img width="813" alt="Bildschirmfoto 2020-07-15 um 19 34 07" src="https://user-images.githubusercontent.com/4953/87571104-30a87680-c6d2-11ea-93cc-3b6ae6b70944.png">

Seems like unzip got interrupted.

**Comment by bettar** [comment]
Can you reproduce the problem consistently ? or is it just one freak occurrence ? What are the steps to reproduce the problem ?
