### ISSUE TITLE
Patient ID hash implementation

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#26]
see https://github.com/zdavatz/amiko_csharp/issues/81#issuecomment-396128272 and https://github.com/zdavatz/AmiKo-iOS/issues/66

**Comment by zdavatz** [comment]
on Mac this `openssl dgst -sha256 mysha` returns `SHA256(mysha)= b1c8e757c035b31d5872a9a4b2309c64b4e23aadd7472f63743dc98ea82977cc`

the mysha file is `davatz.zeno.2.6.1942`

**Comment by bettar** [comment]
on my Mac the same command gives `2666ae74d73f10df8674334476a66b928812c70bb47900cb7e71cb3dcb4db8fa`

**Comment by zdavatz** [comment]
```
/tmp> echo | openssl dgst -sha256 mysha
SHA256(mysha)= b1c8e757c035b31d5872a9a4b2309c64b4e23aadd7472f63743dc98ea82977cc
```

**Comment by zdavatz** [comment]
https://stackoverflow.com/questions/3358420/generating-a-sha-256-hash-from-the-linux-command-line

**Comment by zdavatz** [comment]
```
/tmp> echo -n "davatz.zeno.2.6.1942" | openssl dgst -sha256
(stdin)= 2666ae74d73f10df8674334476a66b928812c70bb47900cb7e71cb3dcb4db8fa
```

**Comment by zdavatz** [comment]
```
/tmp> echo -n davatz.zeno.2.6.1942 | sha256sum
2666ae74d73f10df8674334476a66b928812c70bb47900cb7e71cb3dcb4db8fa
```

**Comment by zdavatz** [comment]
```
zdavatz@MacBookPro:~/Desktop$ echo -n "davatz.zeno.2.6.1942" | openssl dgst -sha256
2666ae74d73f10df8674334476a66b928812c70bb47900cb7e71cb3dcb4db8fa
zdavatz@MacBookPro:~/Desktop$ openssl dgst -sha256 mysha
SHA256(mysha)= b1c8e757c035b31d5872a9a4b2309c64b4e23aadd7472f63743dc98ea82977cc
```

**Comment by zdavatz** [comment]
```
zdavatz@MacBookPro:~/Desktop$ cat mysha
davatz.zeno.2.6.1942
```

**Comment by zdavatz** [comment]
![Bildschirmfoto 2020-08-31 um 15 16 29](https://user-images.githubusercontent.com/4953/91724030-f4a37500-eb9c-11ea-8dc3-1bfcf759a054.png)

**Comment by bettar** [comment]
the terminating `0a` shouldn't be there

**Comment by bettar** [comment]
and file size should be 20 bytes

**Comment by bettar** [comment]
So we can establish that the correct sha256 for your data is `2666ae74d73f10df8674334476a66b928812c70bb47900cb7e71cb3dcb4db8fa`
and not the `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` in issue https://github.com/zdavatz/amiko_csharp/issues/81

**Comment by grauwoelfchen** [comment]
Hi.

Sorry for the confusion about the examples in my issue description. The above @bettar's [comment](https://github.com/zdavatz/amiko_linux/issues/26#issuecomment-683772526) is correct. The value `e3b0c44298...` is not SHA 256 value for `davatz.zeno.2.6.1942`...

Apparently, It seems that it was just for the empty value. I found it ;)

```zsh
% echo -n "" | openssl dgst -sha256
(stdin)= e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

On https://github.com/zdavatz/amiko_csharp/issues/81, I think that I just wanted to describe about its format at the time.

I'll update the description to avoid this confusion for the future. (DONE)

**Comment by bettar** [comment]
As a result of using the SHA256 the userID length has gone up to 64 characters (from the 20 characters in amiko-osx). Consequently we will have very long directory names when saving AMK files.

**Comment by bettar** [comment]
What are we talking about here ? which of the two following uses of UUID:
1. the patient ID used to create a subdirectory for the patien's prescriptions
2. the "prescription hash" (RFC 4122)

**Comment by zdavatz** [comment]
The prescription hash.

**Comment by bettar** [comment]
So how do we calculate the patient Id then ?

**Comment by bettar** [comment]
I think a more meaningful issue title would have been "Patient ID hash implementation", and the answer to my own question is not "2. prescription hash" but "1. patient ID"
