### ISSUE TITLE
Import Addresses

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#30]
1. Go to contacts.google.com (login to Gmail first).
2. Click export. 
3. Choose and export format, i.e. Google-CSV, Outlook-CSV or Vcard.
4. Import the file into the AmiKo-Linux Patients addressbook with the Toogle Button.
5. You can select one, several or all addresses. You should also be able to search in the addresses.
6. Import the selection.
7. Done.

**Comment by bettar** [comment]
Question about point 4. above, do you import every time (every 2 clicks) the toggle button is used, or only once per session ?

**Comment by zdavatz** [comment]
if you click the addressbook item in the bottom right corner on Windows, this window comes every time.

![Bildschirmfoto 2020-09-01 um 14 23 10](https://user-images.githubusercontent.com/4953/91851120-f0d82700-ec5e-11ea-8907-add78303ccc8.png)

**Comment by zdavatz** [comment]
these are the Google Addressbook Export options:
![latest-screenshot](https://user-images.githubusercontent.com/4953/91851430-6c39d880-ec5f-11ea-95bf-f9facdf57500.png)

**Comment by bettar** [comment]
Which one of the 3 options, Google, Outlook, or vCard ?

**Comment by zdavatz** [comment]
good question ;)

**Comment by zdavatz** [comment]
Start with Google, then Outplook then Vcard.

**Comment by bettar** [comment]
The Google CSV doesn't seem to contain email and phone numbers. Outlook CSV does

**Comment by bettar** [comment]
[google.csv.header.txt](https://github.com/zdavatz/amiko_linux/files/5200721/google.csv.header.txt)

**Comment by bettar** [comment]
[outlook.csv.header.txt](https://github.com/zdavatz/amiko_linux/files/5200723/outlook.csv.header.txt)

**Comment by zdavatz** [comment]
```
/tmp> head -1 contacts.csv 
Name,Given Name,Additional Name,Family Name,Yomi Name,Given Name Yomi,Additional Name Yomi,Family Name Yomi,Name Prefix,Name Suffix,Initials,Nickname,Short Name,Maiden Name,Birthday,Gender,Location,Billing Information,Directory Server,Mileage,Occupation,Hobby,Sensitivity,Priority,Subject,Notes,Language,Photo,Group Membership,E-mail 1 - Type,E-mail 1 - Value,E-mail 2 - Type,E-mail 2 - Value,E-mail 3 - Type,E-mail 3 - Value,E-mail 4 - Type,E-mail 4 - Value,IM 1 - Type,IM 1 - Service,IM 1 - Value,Phone 1 - Type,Phone 1 - Value,Phone 2 - Type,Phone 2 - Value,Phone 3 - Type,Phone 3 - Value,Phone 4 - Type,Phone 4 - Value,Address 1 - Type,Address 1 - Formatted,Address 1 - Street,Address 1 - City,Address 1 - PO Box,Address 1 - Region,Address 1 - Postal Code,Address 1 - Country,Address 1 - Extended Address,Address 2 - Type,Address 2 - Formatted,Address 2 - Street,Address 2 - City,Address 2 - PO Box,Address 2 - Region,Address 2 - Postal Code,Address 2 - Country,Address 2 - Extended Address,Organization 1 - Type,Organization 1 - Name,Organization 1 - Yomi Name,Organization 1 - Title,Organization 1 - Department,Organization 1 - Symbol,Organization 1 - Location,Organization 1 - Job Description,Organization 2 - Type,Organization 2 - Name,Organization 2 - Yomi Name,Organization 2 - Title,Organization 2 - Department,Organization 2 - Symbol,Organization 2 - Location,Organization 2 - Job Description,Website 1 - Type,Website 1 - Value,Website 2 - Type,Website 2 - Value,Custom Field 1 - Type,Custom Field 1 - Value
```
[header_google_addresses_zeno.txt](https://github.com/zdavatz/amiko_linux/files/5230585/header_google_addresses_zeno.txt)

**Comment by zdavatz** [comment]
Lets test with Name, Vorname, Adresse, Wohnort, PLZ, Land, Geburtstag, Geschlecht, Telefon, Email

![latest-screenshot](https://user-images.githubusercontent.com/4953/93307354-29503700-f801-11ea-89db-a09653bd2eab.png)

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/93307477-4dac1380-f801-11ea-9ae2-1247638d6d48.png)

**Comment by zdavatz** [comment]
This seems to work!
