### ISSUE TITLE
No save button in patients management

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#31]
![latest-screenshot](https://user-images.githubusercontent.com/4953/91956256-b45f0680-ed04-11ea-8a89-2a5638912fb8.png)

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/91956816-80d0ac00-ed05-11ea-9918-9eb1da126c96.png)

**Comment by zdavatz** [comment]
This is Ubuntu
![Bildschirmfoto 2020-09-02 um 10 18 47](https://user-images.githubusercontent.com/4953/91956983-b9708580-ed05-11ea-84f5-e3a9cc21f15a.png)

**Comment by zdavatz** [comment]
this Doctor signature on Ubuntu.

![Bildschirmfoto 2020-09-02 um 10 19 52](https://user-images.githubusercontent.com/4953/91957071-da38db00-ed05-11ea-9c99-7d88acdf1d3f.png)

**Comment by bettar** [comment]
This is what it should look like (screenshot from Lubuntu)
![Screenshot_2020-09-02_10-38-15](https://user-images.githubusercontent.com/9733270/91959271-af03bb00-ed08-11ea-85d0-689598d06dd2.png)

**Comment by bettar** [comment]
This is what it should look like (screenshot from macOS)
![Screenshot 2020-09-02 at 10 43 14](https://user-images.githubusercontent.com/9733270/91959669-32251100-ed09-11ea-8b88-c838c591f63d.png
)

**Comment by zdavatz** [comment]
How does it look on `Lubuntu`?

**Comment by bettar** [comment]
On Lubuntu it looks like the second last screenshot above

**Comment by zdavatz** [comment]
If I now click save, the app crashes with the following message: 
![latest-screenshot](https://user-images.githubusercontent.com/4953/91968868-977eff00-ed15-11ea-968b-e1ca75b18628.png)

**Comment by bettar** [comment]
It doesn't look like an error message. Anyway, I cannot reproduce this crash in Ubuntu

**Comment by zdavatz** [comment]
Did you build from source on Ubuntu?

**Comment by bettar** [comment]
No, I didn't rebuild from sources on Ubuntu. What's the reasoning behind your question ?

**Comment by zdavatz** [comment]
If you build from sources then you will get crash.

**Comment by bettar** [comment]
I build from sources on Lubuntu and macOS and don't get a crash. What makes you sure that building from sources on Gentoo and Ubuntu would get a crash?

**Comment by zdavatz** [comment]
Good Question. Closing till further notice.
