### ISSUE TITLE
we need a quit button

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#36]
We need a `Quit` menu item.

Firefox has a quit button like this:

![image](https://user-images.githubusercontent.com/4953/93183466-4fab9f00-f73b-11ea-96ec-1c56408ba8fe.jpeg)

**Comment by bettar** [comment]
On which OS and with which Window Manager is this a problem ?

**Comment by zdavatz** [comment]
Gentoo, i3.

**Comment by bettar** [comment]
Then the issue should be brought up to the attention of the WxWidgets team, to make the Quit menu appear on Gentoo/i3, because on all other platforms the Quit menu is there. How many users running Gentoo/i3 do you expect ? Those rare users will probably be power users and know how to quit the application with the usual keyboard shortcut, which by the way is `Modkey+Shift+Q` and not `Strg+Q`

**Comment by zdavatz** [comment]
same problem on Ubuntu: 
![Bildschirmfoto 2020-09-15 um 11 44 41](https://user-images.githubusercontent.com/4953/93194905-e763ba00-f748-11ea-9421-ea31056b8b11.png)

**Comment by bettar** [comment]
In my Ubuntu the Quit menu is there, at the top of the screen
![Screenshot 2020-09-15 at 11 50 09](https://user-images.githubusercontent.com/9733270/93195618-bfc12180-f749-11ea-8b15-0612127f0591.png)

**Comment by zdavatz** [comment]
Yes, that is there too for me. But it is not in the Menu like it should be.

**Comment by bettar** [comment]
On macOS the AmiKo submenu is provided by the wxWidgets framework

![Screenshot 2020-09-16 at 09 22 52](https://user-images.githubusercontent.com/9733270/93305056-46cfd180-f7fe-11ea-8f4c-982d2e725e38.png)

**Comment by zdavatz** [comment]
This is Gimp:
![Bildschirmfoto 2020-09-16 um 09 24 59](https://user-images.githubusercontent.com/4953/93305281-93b3a800-f7fe-11ea-9f1b-27424c622024.png)

**Comment by zdavatz** [comment]
This Inkscape
![Bildschirmfoto 2020-09-16 um 09 27 25](https://user-images.githubusercontent.com/4953/93305470-d83f4380-f7fe-11ea-9d64-34a27da25e03.png)
