### ISSUE TITLE
Importing amk File with new patient Hash creates a new patient.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#41]
1. Create an .amk file with AmiKo-Windows. File has a SHA256 patient Hash.
2. Import the File in AmiKo-Linux.
3. If patient SHA256 does not exist in AmiKo-Linux, a new patient is created, together with the prescription data.
4. If the SHA256 patient Hash exists then the prescription is added to the patient.
5. Drag and Drop on macOS and Linux should work.
6. Import via Menu "Rezept" -> "Rezept laden" should work.

Also see: https://github.com/zdavatz/amiko_csharp/issues/125

**Comment by zdavatz** [comment]
partially solved with: 0cafd2bd398b8da78a4fd66802024484f294d40e

**Comment by zdavatz** [comment]
Drag and Drop does not seem to work on Linux yet.
![Bildschirmfoto 2020-09-28 um 15 04 22](https://user-images.githubusercontent.com/4953/94435945-1859db00-019c-11eb-82fd-ada6595ea403.png)
1. Create new patient on MacOS
2. Add package to prescription.
3. Drag AMK file to the Desktop.
4. Import AMK file to AmiKo Linux.
5. Nothing shows on Linux. Not patient or prescription data is imported.

**Comment by bettar** [comment]
How do you "import" ? By drag&drop or from the "Load prescription" menu ? (the screenshot you posted shows patient data, how is that an illustration of "no patient data is imported" ? Please show the "Patient Suchen" view after the import.

**Comment by zdavatz** [comment]
On macOS Drag-and-Dropping a prescription into AmiKo-WX for macOS created on Windows should work.
