### ISSUE TITLE
Saving doctor address gives warning and does not survive a restart

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#42]
![latest-screenshot](https://user-images.githubusercontent.com/4953/93858623-b9d4be80-fcbc-11ea-8d50-e9c37e472b3f.png)

Also if you restart the Application then the Doctors Address is gone.

**Comment by bettar** [comment]
It's worth noting that the problem affects the Linux build, whereas the macOS build seems to work fine.

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/93999068-a77a8380-fd95-11ea-9f19-ff60a128910c.png)

**Comment by zdavatz** [comment]
works!

**Comment by zdavatz** [comment]
60237e9a8152d6eae6cbea15a4ce47bfc87ed03b

![latest-screenshot](https://user-images.githubusercontent.com/4953/94429029-ff4c2c80-0191-11eb-92bc-482444871631.png)

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/94430480-476c4e80-0194-11eb-99b6-96b7d0599d97.png)
![latest-screenshot](https://user-images.githubusercontent.com/4953/94430507-53581080-0194-11eb-9c12-d00d720c2b88.png)
![latest-screenshot](https://user-images.githubusercontent.com/4953/94430544-636ff000-0194-11eb-9e13-85d147fbf419.png)

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/94430718-a6ca5e80-0194-11eb-9627-744aa75eee97.png)
![latest-screenshot](https://user-images.githubusercontent.com/4953/94430773-b8ac0180-0194-11eb-8ac4-d704d5a40256.png)

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/94430946-f741bc00-0194-11eb-9a3b-2758441efd6e.png)
