### ISSUE TITLE
First AMK Linux file crashes AmiKo-Windows 

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#43]
[RZ_2020-09-22T102431.amk.txt](https://github.com/zdavatz/amiko_linux/files/5260353/RZ_2020-09-22T102431.amk.txt)

**Comment by bettar** [comment]
The Linux amk file implementation is work-in-progress. Still, it would be interesting to know if there are any error messages in amiko-windows  before it crashes.

**Comment by zdavatz** [comment]
Above commit is for #46
