### ISSUE TITLE
Doctor has name twice

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#45]
![latest-screenshot](https://user-images.githubusercontent.com/4953/93979695-f5838d00-fd7d-11ea-87da-d5355f918d7a.png)

**Comment by bettar** [comment]
The macOS build is not affected by this problem
![Screenshot 2020-09-23 at 12 45 01](https://user-images.githubusercontent.com/9733270/94002804-b0218880-fd9a-11ea-839f-57c5ce4181a5.png)

**Comment by zdavatz** [comment]
After the last commit I now get: 
![latest-screenshot](https://user-images.githubusercontent.com/4953/94006514-3c827a00-fda0-11ea-999a-8a1600bb5c17.png)

**Comment by bettar** [comment]
Try copying the `lang` subdirectory from the sources into ~/.AmiKo
Eventually all this should be taken care of by the installer

**Comment by zdavatz** [comment]
this works!

**Comment by zdavatz** [comment]
After [commit](322ec01d555a8f0c86236cc415d29d5244492185) I am getting this: 
![latest-screenshot](https://user-images.githubusercontent.com/4953/94126730-44055a00-fe58-11ea-8909-b72974f13379.png)

The reason for above warning was this https://github.com/zdavatz/amiko_linux#config-hack

**Comment by zdavatz** [comment]
comment out this line: https://github.com/zdavatz/amiko_linux/blob/master/main.cpp#L69

**Comment by zdavatz** [comment]
solved with: https://github.com/zdavatz/amiko_linux/commit/f483f658b6177e7258cf0dffda86bac600b27672#diff-118fcbaaba162ba17933c7893247df3a
