### ISSUE TITLE
Save new patient from existing patient

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#47]
1. Select Patient A.
2. Change first name and birthday of patient A.
3. Click `Save`.
4. Patient is not saved.

or

1. Select Patient A.
2. Change first name of patient A.
3. Click `Save`.
4. Patient is not saved.

**Comment by bettar** [comment]
If you change the name or birthday, you end up with a different patient hash. That would become a new patient. To create a new patient now, you first have to click the Plus button on the right. I think we somehow have to make it clear to the user whether they are editing the current patient or creating a new patient.

**Comment by zdavatz** [comment]
Suggestion by @bettar: When editing an existing Patient change Button name to "Update" (DE: "Aktualisieren"). When you change Name, Surname or Date of Birth change the Button name to "New" (DE: "Neu")

**Comment by zdavatz** [comment]
this must be related: https://ywesee.slack.com/files/U27FC8WLA/F01J3K575HB/update_not_working.mov
