### ISSUE TITLE
lang Dir has to be automatically copied to ~/.AmiKo

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#49]
lang Dir has to be automatically copied to `~/.AmiKo`. Currently this is done manually. See #45 and #10

**Comment by zdavatz** [comment]
I think it would be good if the `lang` dir would also be copied when running `./build.sh`

**Comment by zdavatz** [comment]
after the last commit I get:

![latest-screenshot](https://user-images.githubusercontent.com/4953/94118221-82e1e280-fe4d-11ea-949e-0232995b2bc7.png)

**Comment by bettar** [comment]
The last commit only copies `lang/` into `~/.AmiKo/lang/`. If you undo this by manually deleting `~/.AmiKo/lang/` does the error go away ? It seems to contradict the conclusion at the end of issue #45

**Comment by zdavatz** [comment]
The error stays the same. I am on commit 322ec01d555a8f0c86236cc415d29d5244492185

**Comment by zdavatz** [comment]
this is my steps.conf
```
#STEP_DOWNLOAD_SOURCES_SQLITE=y
#STEP_DOWNLOAD_SOURCES_WXWIDGETS=y
#STEP_INFO_WXWIDGETS=y
#STEP_CONFIGURE_WXWIDGETS=y
#STEP_COMPILE_WXWIDGETS=y

#STEP_CONFIGURE_JSON=y
#STEP_BUILD_JSON=y

STEP_CONFIGURE_APP=y
STEP_COMPILE_APP=y
STEP_COPY_LANG_FILES=y
#STEP_CREATE_INSTALLER_FROM_CLI=y
```
