### ISSUE TITLE
amk file format: add quantity

### ISSUE THREAD

**Issue by bettar** [zdavatz/amiko_linux#51]
When a medicine "package" is added to a prescription it should be possible to specify also the **quantity**, i.e., how many of those packages should be given to the patient when he/she takes the prescription to the pharmacy.

**Comment by zdavatz** [comment]
this is actually a Use-Case that is very rare for prescriptions directly to patients. But it could be very interesting for using AmiKo/CoMed to manage and reshelf your stock as a doctor.

**Comment by bettar** [comment]
So what's the purpose of creating an amk file ? Who will use it ?

**Comment by bettar** [comment]
So what's the purpose of creating an amk file ? Who is going to use it ?

**Comment by zdavatz** [comment]
Doctors, Pharmacists, Patients, etc.

**Comment by bettar** [comment]
So is it a rare Use-Case for pharmacists having to know how many packages to sell to the patient ? Do they sell always only one package in Switzerland ?
