### ISSUE TITLE
syntax error while parsing value - invalid string: missing closing quote;

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#52]
```
jsonStr: [json.exception.parse_error.101] parse error at line 51, column 63: syntax error while parsing value - invalid string: missing closing quote; last read: '"d05ab672-a05d-4ba6-994b-1eaa582c8e3e'
```
![latest-screenshot](https://user-images.githubusercontent.com/4953/94715435-bc36b880-034d-11eb-919f-bc6a7a98cdf9.png)

**Comment by bettar** [comment]
As usual, it helps to know the OS, the steps, and whether or not the problem happens consistently or occasionally. I have feeling that if you inspect that particular amk file with external tools, chances are that it is corrupted/truncated, so the real problem is somewhere else, that is, creating the amk file, not reading it.

**Comment by zdavatz** [comment]
This happens persistently on Linux when moving up and down with the cursor between the AMK file list.

![latest-screenshot](https://user-images.githubusercontent.com/4953/94917403-c1f8df00-04b0-11eb-99ec-adf1398824be.png)

happens when moving the blue bar on the right onto a new AMK file.

![latest-screenshot](https://user-images.githubusercontent.com/4953/94917466-de951700-04b0-11eb-9d6a-940ae93331ba.png)

**Comment by zdavatz** [comment]
These are my AMK files. [patient.tar.gz](https://github.com/zdavatz/amiko_linux/files/5317569/patient.tar.gz)

**Comment by bettar** [comment]
I checked the first 3 files in the tar archive and they are all truncated. I suggest you delete all of them and recreate them.

**Comment by zdavatz** [comment]
Works, closing the issue.

**Comment by zdavatz** [comment]
going up and down again creates the output:
```
void MainWindow::savePrescription() Line:843 TODO
jsonStr: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
jsonStr: [json.exception.parse_error.101] parse error at line 81, column 59: syntax error while parsing value - invalid string: missing closing quote; last read: '"645ebcb1-98ec-47e3-a4c2-b40cd798'
jsonStr: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
jsonStr: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
jsonStr: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
```

**Comment by zdavatz** [comment]
[patient_new.tar.gz](https://github.com/zdavatz/amiko_linux/files/5317751/patient_new.tar.gz)

**Comment by bettar** [comment]
After some debugging I'm inclined to believe that there is a problem in the way the base64 encoding step is used. Need further investigation.

**Comment by zdavatz** [comment]
this is still happening. https://ywesee.slack.com/files/U27FC8WLA/F01BLRWTR0X/issue_52.mov

**Comment by zdavatz** [comment]
I am also seeing this error `[json.exception.type_error.302] type must be string, but is null`

**Comment by zdavatz** [comment]
this seems to be caused by missing GTIN codes.
