### ISSUE TITLE
Search selection jumps back

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#53]
1. Select "Präparat".
2. Select "Searchbar".
3. Selection of "Präparat" is lost.

![Bildschirmfoto 2020-10-01 um 08 31 25](https://user-images.githubusercontent.com/4953/94775683-98f92100-03c0-11eb-91f6-9a232f68fe69.png)

**Comment by bettar** [comment]
Confirmed. It seems to work only on the macOS build.

**Comment by zdavatz** [comment]
seems to work.
