### ISSUE TITLE
Applications crashes when deleting a line in interactions view

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#56]
![interactions_crash](https://user-images.githubusercontent.com/4953/94905027-7d634880-049c-11eb-8d2c-24a824133800.png)

The name of the Button should be `Löschen`. The translations is missing is `lang/de/amiko.po`.

**Comment by bettar** [comment]
I cannot actually reproduce the crash (Lubuntu, Ubuntu, macOS) but there is some more work to be done in this area.

**Comment by bettar** [comment]
After fixing some other problems, I could reproduce the crash on Lubuntu. Now I get
`Error sending IPC message: Broken pipe`

**Comment by zdavatz** [comment]
Application no longer crashes but the delete icon is missing. 

![latest-screenshot](https://user-images.githubusercontent.com/4953/98953112-8e23c700-24fc-11eb-9aef-3503d4f07d6d.png)
