### ISSUE TITLE
Strg+A is still not working.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#57]
Strg+A and Strg+L are **not** working.

Strg+Q is working.

**Comment by bettar** [comment]
Confirmed.
The accelerator key CTRL+A works only in the macOS build for now.
CTRL+L is not implemented yet.

**Comment by zdavatz** [comment]
seems to work again.

**Comment by zdavatz** [comment]
Strg+Q
Strg+L
are now working.

Strg+A is still not working.
