### ISSUE TITLE
Delete a prescription with all medicines

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#58]
Using backspace or the `-` should be able to delete prescription with all packages in the prescription.

**Comment by bettar** [comment]
Are you talking about the - button in the patient search panel (the one next to the + button) ?

**Comment by zdavatz** [comment]
The one that will be here, same as in macOS.

![delete_prescription](https://user-images.githubusercontent.com/4953/94917269-84945180-04b0-11eb-9562-dc6ba11043c5.png)
