### ISSUE TITLE
Prespcriptions are not shown after restarting the App and selecting the patient.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#59]
Video summary of the issue: https://ywesee.slack.com/files/U27FC8WLA/F01C5AJA5FD/issue_59.mov

Prespcriptions are not shown after restarting the App and selecting the patient.

1. Add patient A.
2. Add four prescriptions for patient A.
3. Save each presctiption as new.
4. Restart the App.
5. Double click on patient A.
6. No prescriptions are shown.
7. Add a new prescription for patient A. 
8. Click save as new.
9. Now all prescriptions are shown. 
10. Scrolling throught the prescriptions results in #52 and in
![Bildschirmfoto 2020-10-07 um 18 13 09](https://user-images.githubusercontent.com/4953/95350999-6ae87500-08c9-11eb-8095-bf5776e2bdcb.png)
11. Also see: https://ywesee.slack.com/files/U27FC8WLA/F01BLRWTR0X/issue_52.mov

**Comment by bettar** [comment]
Workaround: as soon as the the app starts up, select any fachinfo, then it works as expected (tested on macOS).

**Comment by zdavatz** [comment]
This should work without workaround. It should just work.
