### ISSUE TITLE
Patient Address is cut off in prescription window

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#61]
![Bildschirmfoto 2020-10-11 um 18 22 13](https://user-images.githubusercontent.com/4953/95682601-bf079800-0bee-11eb-8b12-87cfaad63236.png)

**Comment by bettar** [comment]
I cannot reproduce this problem in Lubuntu, nor in macOS. For which OS are you experiencing the problem ?

**Comment by zdavatz** [comment]
Gentoo. Please share a screenshot. How many lines do you have?

**Comment by zdavatz** [comment]
This is Ubuntu: 
![Bildschirmfoto 2020-11-03 um 19 07 15](https://user-images.githubusercontent.com/4953/98017406-df9aca80-1e07-11eb-8d4f-740e5f70294e.png)

**Comment by bettar** [comment]
![Lubuntu-system-font-8](https://user-images.githubusercontent.com/9733270/98248369-1f32f500-1f75-11eb-969d-d2488e4e9d67.png)
Lubuntu with system font size set to 8

**Comment by bettar** [comment]
![Lubuntu-system-font-12](https://user-images.githubusercontent.com/9733270/98248449-396cd300-1f75-11eb-841e-f0be8ab805c3.png)
Lubuntu with system font size set to 12

**Comment by bettar** [comment]
![Ubuntu](https://user-images.githubusercontent.com/9733270/98248472-438ed180-1f75-11eb-99c4-4b1e228fa556.png)
Ubuntu 20.04 with default system font size

**Comment by zdavatz** [comment]
can you force the window to Auto-Resize? Try with font size 14. This is from Commit: cda18037c77c10dee42cf6c953c4115555a3d32a

**Comment by bettar** [comment]
What worries me in your screenshot is that the doctor's signature PNG is not loaded. I guess the layout depends on the vertical size of that signature.

**Comment by zdavatz** [comment]
can we resize the doctor image?

**Comment by zdavatz** [comment]
now it is even more cutoff.

![Bildschirmfoto 2020-11-06 um 15 47 45](https://user-images.githubusercontent.com/4953/98373117-71444b00-2047-11eb-8e86-a5b2e5e16246.png)
