### ISSUE TITLE
Funtoo does not find SCM Microsystems, Inc. CLOUD 2700 R Smart Card Reader as normal user

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#64]
https://bugs.funtoo.org/browse/FL-7563

getting `SCardEstablishContext: RPC transport error.` when running `pcsc_scan`

`Bus 003 Device 005: ID 04e6:5810 SCM Microsystems, Inc. CLOUD 2700 R Smart Card Reader`

**Comment by bettar** [comment]
There is nothing that can be done in this project to address this issue

**Comment by zdavatz** [comment]
This is issue has been resolved, see: https://bugs.funtoo.org/browse/FL-7563?focusedCommentId=46328&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-46328

and 

https://github.com/LudovicRousseau/pcsc-tools/issues/40#issuecomment-717491497
