### ISSUE TITLE
Keep color of (red and green)

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#68]
When you select the cell you lose the color red and green.

![latest-screenshot](https://user-images.githubusercontent.com/4953/97558429-669d0c80-19dc-11eb-801d-4c0334cf03eb.png)
![latest-screenshot](https://user-images.githubusercontent.com/4953/97558477-761c5580-19dc-11eb-9305-4ba7f9a3bad8.png)

**Comment by bettar** [comment]
It got broken since the commit that sets the background to a custom color. It used to work with the default selection color.
