### ISSUE TITLE
Implement Google Cloud Sync for AmiKo Linux

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#76]
The AmiKo Linux User should be able to sync with Windows and Android via Google Cloud Sync.

See also:
https://github.com/zdavatz/amiko_csharp/issues/227
https://github.com/zdavatz/AmiKo-Android/issues/174

This is already possible with between Android and Windows. Now lets hook in Linux as well.

**Comment by b123400** [comment]
Todo list:

- [x] Preferences window
  - [x] Localization
- [x] Show google OAuth page
- [x] Extract code
- [x] Exchange code with tokens
  - [x] Save access token, refresh tokens, expiry
- [ ] Renew access token
- [ ] Get list of files in drive
- [ ] Access file's content in drive (download)
- [ ] Access file's metadata in drive
- [ ] Upload file
- [ ] Update metadata
- [ ] Delete file
- [ ] Sync doctor files
  - [ ] info
  - [ ] avatar
- [ ] Sync amk files (amk)
- [ ] Patient data
- [ ] Update AMK List UI after sync
- [ ] Update doctor view after sync
- [ ] Update Patient UI after sync
  - [ ] Patient list
  - [ ] Patient detail

**Comment by zdavatz** [comment]
thank you for the todo list!

**Comment by b123400** [comment]
Don't know why the Todo-List is gone, I am writing it again 😐

- [x] OAuth with Google
- [x] Preference UI
- [x] Sync doctor files
  - [x] signature file
  - [x] doctor.json
- [x] Favourites
- [x] Sync patients
  - [x] Create
  - [x] Update
  - [x] Download
  - [x] Delete
- [ ] Update doctor UI when files are changed
- [ ] Update AMK list when files are changed
- [ ] Update patient UI
- [ ] Trigger sync when files are changed
  - [ ] AMK
  - [ ] Doctor
  - [ ] Favourites
  - [ ] Patients
- [ ] Auto update

**Comment by b123400** [comment]
Updated todo list:

- [x] OAuth with Google
- [x] Preference UI
- [x] Sync doctor files
  - [x] signature file
  - [x] doctor.json
- [x] Favourites
- [x] Sync patients
  - [x] Create
  - [x] Update
  - [x] Download
  - [x] Delete
- [x] Update doctor UI when files are changed
- [x] Update AMK list when files are changed
- [x] Update patient UI
- [x] Trigger sync when files are changed
  - [x] AMK
  - [x] Doctor
  - [x] Favourites
  - [x] Patients
- [x]  Auto update
