### ISSUE TITLE
Implement Label Printer

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#81]
See:

https://github.com/zdavatz/amiko-osx/issues/16
https://github.com/zdavatz/AmiKo-iOS/issues/76

**Comment by zdavatz** [comment]
Label printing is still a bit off, after commit: cec84bc873da09e979519d7aeb493e7292ad71f2
![latest-screenshot](https://user-images.githubusercontent.com/4953/102336460-7b842e00-3f91-11eb-8ccb-2895cbe7021a.png)

**Comment by bettar** [comment]
That commit was not addressing the label printing. So far there hasn't been any commit addressing issue #81
