### ISSUE TITLE
Build fails on Ubuntu

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#89]
[CMakeOutput.log](https://github.com/zdavatz/amiko_linux/files/5589683/CMakeOutput.log)

![Bildschirmfoto 2020-11-24 um 13 04 19](https://user-images.githubusercontent.com/4953/100091955-9e6d6780-2e55-11eb-858e-189db70978d4.png)

since commit: 8135cf4f67f5386c4a4d03f44b2a993c7c287a9b - https://github.com/zdavatz/amiko_linux/pull/86

**Comment by b123400** [comment]
Can you try:

```
sudo apt install libcurl4-openssl-dev
```

**Comment by zdavatz** [comment]
This works! It is also in the README, great!
