### ISSUE TITLE
add CONFIG_DB_DIR="" to seed.in.conf

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#9]
```
2020-06-25 09:07:31.230643+0200 AmiKo[88918:12323103] Metal API Validation Enabled
2020-06-25 09:07:31.299385+0200 AmiKo[88918:12323375] flock failed to lock maps file: errno = 35
2020-06-25 09:07:31.318881+0200 AmiKo[88918:12323375] flock failed to lock maps file: errno = 35
bool DBAdapter::openDatabase(wxString) amiko_db_full_idx_de
Didn't find /Users/zdavatz/Library/Application Support/AmiKo/amiko_db_full_idx_de.db
Number of records in AIPS database: (lldb) 
```

**Comment by zdavatz** [comment]
DB files should be searched for in `~/.AmiKo` or `~/.CoMed`. Also the build script needs to download the files there.

**Comment by zdavatz** [comment]
Downloads as well as the initial DB files will be in the same directory:
- $CONFIG_DB_DIR/.AmiKo
- $CONFIG_DB_DIR/.CoMed

**Comment by bettar** [comment]
My preference would be to use the default directories returned by the wxWidgets library for "UserData", which on the Linux platform resolves respectively to:
- ~/.AmiKo
- ~/.CoMed
The same location should be used also for CSS and JS files.

**Comment by zdavatz** [comment]
Yes, I agree. See https://github.com/zdavatz/amiko_linux/issues/9#issuecomment-649290454

**Comment by zdavatz** [comment]
this also works now after commit: 322ec01d555a8f0c86236cc415d29d5244492185
