### ISSUE TITLE
Can no longer add packages to the prescription

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#92]
This is happening since commit 92a635c435dd9aba61506d4195a5eed09b31e4f7

1. Open App.
2. Select prescription Tab.
3. Select patient.
4. Add package to prescription.
5. Package is not added to the prescription.

Interesting observation: If I first print a Fachinfo, then I can add a package to the prescription afterwards. I think the printing commit messed something up in the main window. Confirmed on Gentoo and Ubuntu. On Ubuntu it also seems that you can not longer click anything in the main window if you do not first print a Fachinfo.

**Comment by bettar** [comment]
The printing commit is not the culprit. I think it's been like this since commit 7039ade "Initially no selection" of 3 Nov 2011.

**Comment by zdavatz** [comment]
Well I noticed it since the printing commit.
