### ISSUE TITLE
Clicking on FTS Favorites crashes the App

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#93]
1. Open the App.
2. Add a package to the prescription.
3. Click `Prescription`.
4. Select a patient.
5. Add two more packages to the patient.
6. Save as new prescription.
7. Click Favorites.
8. Click FTS Favorites. 
9. App crashes.

**Comment by bettar** [comment]
Any error messages logged to the console ?

**Comment by zdavatz** [comment]
No, unfortunately not.

**Comment by zdavatz** [comment]
Currently I can also not reproduce it.
