### ISSUE TITLE
Search result still sometimes shows "null" value

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#97]
![latest-screenshot](https://user-images.githubusercontent.com/4953/100908268-9c497f80-34cb-11eb-9e47-c47c0368fa52.png)

**Comment by bettar** [comment]
I have a feeling that UTF8 support is not completely configured on those machines. Those medicine titles contain some "unusual" symbol like a registration mark ®
It shouldn't be difficult to fix in the app.

**Comment by zdavatz** [comment]
Ok!

**Comment by zdavatz** [comment]
works, with ea235823757eb97b9a62bb9d57dee48c6f917e44 but was fixed earlier ;)
