### ISSUE TITLE
Can not set locale to Language German

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#98]
On my GentooX Test machine, this still pops up.

![latest-screenshot](https://user-images.githubusercontent.com/4953/100997137-3d7f1700-355a-11eb-98dc-708c060ef767.png)

[can_not_set_locale_to_language_German.txt](https://github.com/zdavatz/amiko_linux/files/5635398/can_not_set_locale_to_language_German.txt)

**Comment by bettar** [comment]
It's not an error, it's just reporting that the German locale is not available on that system. Try to run the command `locale -a` and see if German is available. Interesting to note that a lot of the issues so far are about your Gentoo installation.

**Comment by zdavatz** [comment]
zdavatz@localhost ~/Applications/AmiKo-wx/AmiKo $ locale -a
```
C
C.utf8
POSIX
de_CH.utf8
```
So yes, the German is available.

**Comment by bettar** [comment]
It is available but not configured, see:
[Configure locales](https://www.thomas-krenn.com/en/wiki/Configure_Locales_in_Ubuntu#No_locale_set)

or maybe the problem is that the app now tries to set the locale to `wxLANGUAGE_GERMAN`, instead of `wxLANGUAGE_GERMAN_SWISS`

**Comment by zdavatz** [comment]
@bettar recommends to comment this out.

**Comment by zdavatz** [comment]
for Gentoo this should help: `sudo localedef -i de_CH -f UTF-8 de_CH.UTF-8`
